### ISSUE TITLE
3 things to add

### ISSUE THREAD

**Issue by cssobral2013** [bettergui/BeVietnam#1]
- Add U+0141 (Ł), U+0142 (ł), U+0150 (Ő), U+0151 (ő), U+0170 (Ű) and U+0171 (ű) and its alternates (this is required for Central European);

- Add tabular figures;

- make f in ligatures descend

**Comment by yellow-type-foundry** [comment]
@cssobral2013 Thank you for the request, we'll make those updates for the upcoming version.

**Comment by cssobral2013** [comment]
OP was updated to include full support for Central European.

**Comment by cssobral2013** [comment]
This issue will be closed, as it looks like the font has gained a major update.

**Comment by yellow-type-foundry** [comment]
@cssobral2013 Yes indeed, stay tuned!
