### ISSUE TITLE
Recent build defaults to alternate characters?

### ISSUE THREAD

**Issue by djmtype** [bettergui/BeVietnam#5]
I don't know if it's my computer, but the recent build looks like an entirely different typeface. Tested: InDesign, Figma, Sketch. The typeface might be falling back to something else?

![Screen Shot 10](https://user-images.githubusercontent.com/930713/120562623-c32e3300-c3d4-11eb-804e-3690a07b9123.png)

However, it's previewing fine in RightFont. 

![Screen Shot 11](https://user-images.githubusercontent.com/930713/120562852-418ad500-c3d5-11eb-897a-40cc65cd03ec.png)

**Comment by djmtype** [comment]
I just cleared my font cache. Now RightFont is displaying the same as all the rest. Has this font been redesigned?

**Comment by yellow-type-foundry** [comment]
Hi @djmtype, yes we're updating the typeface, the one you're seeing is probably an earlier version (with that double storey a).

**Comment by djmtype** [comment]
It's still sleek – different now. But I thought the old version had a bit more character (pun intended). Looking at the lowercase "g", "a", "l" characters and the italicized variants.
